SOURCES := $(wildcard *.cpp)

CXXFLAGS := -std=c++11 -O0 -ggdb

#TODO generate app executable
app : $(SOURCES)
	g++ $(CXXFLAGS) $(SOURCES) -o app 

.PHONY : clean






















































