SOURCES := $(wildcard *.c)

CXXFLAGS := -std=c++11 -O0 -ggdb

app : $(SOURCES)
	g++ $(CXXFLAGS) $(SOURCES) -o app 

PROGRAM := hw1_jnaky4

.PHONY : clean

clean :
	-rm -rf $(PROGRAM)





















































