PROGRAMS := \
	SegFault_Example \
	gdb-ex1 \
	gdb-ex2 \
	gdb-ex3 \
	gdb-ex4 \

CFLAGS := -std=c11 -O0 -ggdb -fno-stack-protector

.PHONY : all
all : $(PROGRAMS)

.PHONY : clean
clean :
	rm -rf $(PROGRAMS)

SegFault_Example :

gdb-ex1 :

gdb-ex2 :

gdb-ex3 :

gdb-ex4 :















